### PR TITLE
fix a bug... that I still can't explained

### PR DESCRIPTION
**Pull request by yormi**
Ok so I don't know if this PR will be welcome but if you are interested, here's my story :P

I had a bug within a project with many .babelrc. The output path was not right. I tried to figure out what was wrong but after a while trying to understand the code and pulling my hair out with all those paths, I decided to refactor to try to make it clearer.

It ended up with big changes and noticed a flaw in the plugin tests ('./some/path' will match './../some/path' as well).

Anyway, I solved my bug but with all that, I still can not tell exactly what was causing the problem neither what exactly solved it.

So this is the code if you want to check it out.

### CODE REVIEW

**Comment by per2plex** [comment]
Thanks! The code looks a lot cleaner now, only thing I'll probably change is converting the top level Arrow Functions to normal Functions. 

As soon as I got some time on my hand I'll test it in my projects and merge it if everything works as expected :)

One question though, why's there an `npm-shrinkwrap.json` because it seems to break the dependencies for node versions < 5.x. Accidental commit or does it serve a purpose?

**Comment by yormi** [comment]
Voilà ! No more shrinkwrap !

Annnnd... I don't know, what does it change to have top-level functions as normal functions ? :)

EDIT:
The build is still not passing all the tests. Are those problems you already encountered ? If yes, I would really appreciate if you could tell me what I did wrong.

**Comment by per2plex** [comment]
Don't worry Appveyor just fails occasionally with a network error while installing dependencies. I restart the build till it works. I'll have to look into it sometime, maybe there's a way to fix this :)

EDIT: I see the tests aren't passing, missread your comment. It doesn't seem to unixify the final generated path probably a `slash()` missing somewhere.

**Comment by yormi** [comment]
Alright ! Just let me know if you need anthing :)

**Comment by per2plex** [comment]
Looks good, thanks for your work again! 👍

**Comment by yormi** [comment]
My pleasure, mate !

**Pull request merged**
